spring.application.name=springdatajpademo
spring.datasource.url=jdbc:postgresql://localhost:5432/DemoDb
spring.datasource.username=postgres
spring.datasource.password=Harshal@2003

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

logging.level.org.springframework.security=DEBUG
server.port=8080
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.properties.hibernate.format_sql=false

spring.jpa.defer-datasource-initialization=true
soring.sql.init.node=always
spring.sql.init.data-locations=classpath:data.sql